### ISSUE TITLE
Add Japanese

### ISSUE THREAD

**Issue by fu-sen** [djemos/slackel-live-installer#1]
I am working with Salix on Japanese translation for Slackel. Since they are almost the same.

Japanese was added to Transifex. I have done this work. (`ja`, not `ja-JP` to match other languages)
https://www.transifex.com/djemos/slackel-live-installer/language/ja/

**Comment by djemos** [comment]
Text help is not shown at all. e.g. Put mouse on full installation. No help text appeared.
